source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

project ‘JCFrameworkDemo’

def all_pods
    pod "MagicalRecord"
    pod 'JCFramework', :path => '../JCFramework'
    pod 'JCFloatingView', :path => '../JCFloatingView'

end


target :'JCFrameworkDemo' do
   all_pods
end

target :'JCFrameworkDemoTests' do
    all_pods
end

target :'JCFrameworkDemoUITests' do
    all_pods
end
