source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

project ‘JCFrameworkDemo’

def all_pods
    pod "MagicalRecord"
    pod 'JCFloatingView', :podspec => 'https://raw.githubusercontent.com/EzlyJohnnie/JCUtilsDemo/master/JCFloatingView/JCFloatingView.podspec'
    pod 'JCFramework', :podspec => 'https://raw.githubusercontent.com/EzlyJohnnie/JCUtilsDemo/master/JCFramework/JCFramework.podspec'
end

target :'JCFrameworkDemo' do
   all_pods
end

target :'JCFrameworkDemoTests' do
    all_pods
end

target :'JCFrameworkDemoUITests' do
    all_pods
end
